name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt to check formatting
        run: |
          gofumpt -l -w .
          if [[ $(git status --porcelain) ]]; then
            echo "::error::Go code is not properly formatted. Run 'gofumpt -l -w .' locally to fix."
            git diff
            exit 1
          fi

      - name: Build the binary
        run: go build main.go
